/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LOCK_PERIOD"
      | "MIN_STAKE"
      | "agentList"
      | "agents"
      | "blacklistAgent"
      | "getAgentCount"
      | "getAgentsByCapability"
      | "oracleToken"
      | "owner"
      | "pendingUnstake"
      | "recordSuccess"
      | "registerAgent"
      | "renounceOwnership"
      | "slashStake"
      | "stakeTokens"
      | "stakedAt"
      | "transferOwnership"
      | "unstakeTokens"
      | "updateReputation"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentBlacklisted"
      | "AgentRegistered"
      | "AgentStaked"
      | "AgentUnstaked"
      | "OwnershipTransferred"
      | "ReputationUpdated"
      | "StakeSlashed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "LOCK_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "agentList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "blacklistAgent",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentsByCapability",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingUnstake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordSuccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "slashStake",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakedAt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputation",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "LOCK_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_STAKE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agentList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blacklistAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentsByCapability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingUnstake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordSuccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "slashStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakedAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AgentBlacklistedEvent {
  export type InputTuple = [agent: AddressLike, reason: string];
  export type OutputTuple = [agent: string, reason: string];
  export interface OutputObject {
    agent: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [agent: AddressLike, capabilities: string[]];
  export type OutputTuple = [agent: string, capabilities: string[]];
  export interface OutputObject {
    agent: string;
    capabilities: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentStakedEvent {
  export type InputTuple = [agent: AddressLike, amount: BigNumberish];
  export type OutputTuple = [agent: string, amount: bigint];
  export interface OutputObject {
    agent: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUnstakedEvent {
  export type InputTuple = [
    agent: AddressLike,
    amount: BigNumberish,
    unlockTime: BigNumberish
  ];
  export type OutputTuple = [agent: string, amount: bigint, unlockTime: bigint];
  export interface OutputObject {
    agent: string;
    amount: bigint;
    unlockTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [agent: AddressLike, newReputation: BigNumberish];
  export type OutputTuple = [agent: string, newReputation: bigint];
  export interface OutputObject {
    agent: string;
    newReputation: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeSlashedEvent {
  export type InputTuple = [
    agent: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [agent: string, amount: bigint, reason: string];
  export interface OutputObject {
    agent: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LOCK_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  agentList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        wallet: string;
        stake: bigint;
        reputation: bigint;
        totalRequests: bigint;
        correctResponses: bigint;
        lastActive: bigint;
        blacklisted: boolean;
      }
    ],
    "view"
  >;

  blacklistAgent: TypedContractMethod<
    [agent: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;

  getAgentCount: TypedContractMethod<[], [bigint], "view">;

  getAgentsByCapability: TypedContractMethod<
    [capability: string],
    [string[]],
    "view"
  >;

  oracleToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingUnstake: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  recordSuccess: TypedContractMethod<
    [agent: AddressLike],
    [void],
    "nonpayable"
  >;

  registerAgent: TypedContractMethod<
    [capabilities: string[], dataSources: string[]],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  slashStake: TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  stakeTokens: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakedAt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unstakeTokens: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateReputation: TypedContractMethod<
    [agent: AddressLike, newReputation: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LOCK_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        wallet: string;
        stake: bigint;
        reputation: bigint;
        totalRequests: bigint;
        correctResponses: bigint;
        lastActive: bigint;
        blacklisted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "blacklistAgent"
  ): TypedContractMethod<
    [agent: AddressLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAgentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgentsByCapability"
  ): TypedContractMethod<[capability: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "oracleToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingUnstake"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordSuccess"
  ): TypedContractMethod<[agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [capabilities: string[], dataSources: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slashStake"
  ): TypedContractMethod<
    [agent: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakeTokens"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakedAt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstakeTokens"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateReputation"
  ): TypedContractMethod<
    [agent: AddressLike, newReputation: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AgentBlacklisted"
  ): TypedContractEvent<
    AgentBlacklistedEvent.InputTuple,
    AgentBlacklistedEvent.OutputTuple,
    AgentBlacklistedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentStaked"
  ): TypedContractEvent<
    AgentStakedEvent.InputTuple,
    AgentStakedEvent.OutputTuple,
    AgentStakedEvent.OutputObject
  >;
  getEvent(
    key: "AgentUnstaked"
  ): TypedContractEvent<
    AgentUnstakedEvent.InputTuple,
    AgentUnstakedEvent.OutputTuple,
    AgentUnstakedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StakeSlashed"
  ): TypedContractEvent<
    StakeSlashedEvent.InputTuple,
    StakeSlashedEvent.OutputTuple,
    StakeSlashedEvent.OutputObject
  >;

  filters: {
    "AgentBlacklisted(address,string)": TypedContractEvent<
      AgentBlacklistedEvent.InputTuple,
      AgentBlacklistedEvent.OutputTuple,
      AgentBlacklistedEvent.OutputObject
    >;
    AgentBlacklisted: TypedContractEvent<
      AgentBlacklistedEvent.InputTuple,
      AgentBlacklistedEvent.OutputTuple,
      AgentBlacklistedEvent.OutputObject
    >;

    "AgentRegistered(address,string[])": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentStaked(address,uint256)": TypedContractEvent<
      AgentStakedEvent.InputTuple,
      AgentStakedEvent.OutputTuple,
      AgentStakedEvent.OutputObject
    >;
    AgentStaked: TypedContractEvent<
      AgentStakedEvent.InputTuple,
      AgentStakedEvent.OutputTuple,
      AgentStakedEvent.OutputObject
    >;

    "AgentUnstaked(address,uint256,uint256)": TypedContractEvent<
      AgentUnstakedEvent.InputTuple,
      AgentUnstakedEvent.OutputTuple,
      AgentUnstakedEvent.OutputObject
    >;
    AgentUnstaked: TypedContractEvent<
      AgentUnstakedEvent.InputTuple,
      AgentUnstakedEvent.OutputTuple,
      AgentUnstakedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReputationUpdated(address,uint256)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;

    "StakeSlashed(address,uint256,string)": TypedContractEvent<
      StakeSlashedEvent.InputTuple,
      StakeSlashedEvent.OutputTuple,
      StakeSlashedEvent.OutputObject
    >;
    StakeSlashed: TypedContractEvent<
      StakeSlashedEvent.InputTuple,
      StakeSlashedEvent.OutputTuple,
      StakeSlashedEvent.OutputObject
    >;
  };
}
