/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface OracleHubInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_STAKE"
      | "REWARD_MULTIPLIER"
      | "SLASH_PENALTY"
      | "agentList"
      | "agentRegistry"
      | "agents"
      | "finalizeRequest"
      | "getRequest"
      | "oracleToken"
      | "owner"
      | "renounceOwnership"
      | "requestData"
      | "requests"
      | "setAgentRegistry"
      | "submitResponse"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DataRequested"
      | "OwnershipTransferred"
      | "RequestFinalized"
      | "ResponseSubmitted"
      | "RewardDistributed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MIN_STAKE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "REWARD_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLASH_PENALTY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "finalizeRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "oracleToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestData",
    values: [string, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "requests", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setAgentRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResponse",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "MIN_STAKE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SLASH_PENALTY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "oracleToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAgentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DataRequestedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    requester: AddressLike,
    dataType: string,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    requester: string,
    dataType: string,
    fee: bigint
  ];
  export interface OutputObject {
    requestId: string;
    requester: string;
    dataType: string;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestFinalizedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    result: BytesLike,
    correctCount: BigNumberish,
    incorrectCount: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    result: string,
    correctCount: bigint,
    incorrectCount: bigint
  ];
  export interface OutputObject {
    requestId: string;
    result: string;
    correctCount: bigint;
    incorrectCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResponseSubmittedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    agent: AddressLike,
    data: BytesLike
  ];
  export type OutputTuple = [requestId: string, agent: string, data: string];
  export interface OutputObject {
    requestId: string;
    agent: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    agents: AddressLike[],
    rewards: BigNumberish[]
  ];
  export type OutputTuple = [
    requestId: string,
    agents: string[],
    rewards: bigint[]
  ];
  export interface OutputObject {
    requestId: string;
    agents: string[];
    rewards: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OracleHub extends BaseContract {
  connect(runner?: ContractRunner | null): OracleHub;
  waitForDeployment(): Promise<this>;

  interface: OracleHubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_STAKE: TypedContractMethod<[], [bigint], "view">;

  REWARD_MULTIPLIER: TypedContractMethod<[], [bigint], "view">;

  SLASH_PENALTY: TypedContractMethod<[], [bigint], "view">;

  agentList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        isRegistered: boolean;
        stake: bigint;
        reputation: bigint;
        totalRequests: bigint;
        correctResponses: bigint;
      }
    ],
    "view"
  >;

  finalizeRequest: TypedContractMethod<
    [requestId: BytesLike],
    [string],
    "nonpayable"
  >;

  getRequest: TypedContractMethod<
    [requestId: BytesLike],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        requester: string;
        dataType: string;
        fee: bigint;
        requiredAgents: bigint;
        responseCount: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;

  oracleToken: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestData: TypedContractMethod<
    [
      dataType: string,
      parameters: BytesLike,
      requiredAgents: BigNumberish,
      consensusThreshold: BigNumberish
    ],
    [string],
    "payable"
  >;

  requests: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        requester: string;
        dataType: string;
        parameters: string;
        fee: bigint;
        requiredAgents: bigint;
        consensusThreshold: bigint;
        deadline: bigint;
        finalized: boolean;
        result: string;
      }
    ],
    "view"
  >;

  setAgentRegistry: TypedContractMethod<
    [_agentRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  submitResponse: TypedContractMethod<
    [requestId: BytesLike, data: BytesLike, proof: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REWARD_MULTIPLIER"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLASH_PENALTY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        isRegistered: boolean;
        stake: bigint;
        reputation: bigint;
        totalRequests: bigint;
        correctResponses: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "finalizeRequest"
  ): TypedContractMethod<[requestId: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getRequest"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [
      [string, string, bigint, bigint, bigint, boolean] & {
        requester: string;
        dataType: string;
        fee: bigint;
        requiredAgents: bigint;
        responseCount: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "oracleToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestData"
  ): TypedContractMethod<
    [
      dataType: string,
      parameters: BytesLike,
      requiredAgents: BigNumberish,
      consensusThreshold: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        requester: string;
        dataType: string;
        parameters: string;
        fee: bigint;
        requiredAgents: bigint;
        consensusThreshold: bigint;
        deadline: bigint;
        finalized: boolean;
        result: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAgentRegistry"
  ): TypedContractMethod<[_agentRegistry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitResponse"
  ): TypedContractMethod<
    [requestId: BytesLike, data: BytesLike, proof: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DataRequested"
  ): TypedContractEvent<
    DataRequestedEvent.InputTuple,
    DataRequestedEvent.OutputTuple,
    DataRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RequestFinalized"
  ): TypedContractEvent<
    RequestFinalizedEvent.InputTuple,
    RequestFinalizedEvent.OutputTuple,
    RequestFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "ResponseSubmitted"
  ): TypedContractEvent<
    ResponseSubmittedEvent.InputTuple,
    ResponseSubmittedEvent.OutputTuple,
    ResponseSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;

  filters: {
    "DataRequested(bytes32,address,string,uint256)": TypedContractEvent<
      DataRequestedEvent.InputTuple,
      DataRequestedEvent.OutputTuple,
      DataRequestedEvent.OutputObject
    >;
    DataRequested: TypedContractEvent<
      DataRequestedEvent.InputTuple,
      DataRequestedEvent.OutputTuple,
      DataRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RequestFinalized(bytes32,bytes,uint256,uint256)": TypedContractEvent<
      RequestFinalizedEvent.InputTuple,
      RequestFinalizedEvent.OutputTuple,
      RequestFinalizedEvent.OutputObject
    >;
    RequestFinalized: TypedContractEvent<
      RequestFinalizedEvent.InputTuple,
      RequestFinalizedEvent.OutputTuple,
      RequestFinalizedEvent.OutputObject
    >;

    "ResponseSubmitted(bytes32,address,bytes)": TypedContractEvent<
      ResponseSubmittedEvent.InputTuple,
      ResponseSubmittedEvent.OutputTuple,
      ResponseSubmittedEvent.OutputObject
    >;
    ResponseSubmitted: TypedContractEvent<
      ResponseSubmittedEvent.InputTuple,
      ResponseSubmittedEvent.OutputTuple,
      ResponseSubmittedEvent.OutputObject
    >;

    "RewardDistributed(bytes32,address[],uint256[])": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
  };
}
